shamefullyHoist: true
shellEmulator: true

trustPolicy: off
minimumReleaseAge: 0

autoInstallPeers: true
strictPeerDependencies: false
saveExact: true
allowBuilds:
  '@parcel/watcher': true
  esbuild: true
  sharp: true
  unrs-resolver: true
  vue-demi: false
