fragment LandingEntry on landingPage_Entry {
  ...EntryInterfaceType
  logo {
    ...Media
  }
  images {
    ...Media
  }
  body
  sidebar
  orgSchema {
    ...OrgSchema
  }
  seo {
    ...SEO
  }
}
