fragment PageEntry on pageDefault_Entry {
  ...EntryInterfaceType
  blocks {
    ...Blocks
  }
  seo {
    ...SEO
  }
  orgSchema {
    ...OrgSchemaFieldPieces
  }
}

fragment PageArchiveEntry on pageArchive_Entry {
  ...EntryInterfaceType
  archiveType
  projectCategory {
    id
  }
  seo {
    ...SEO
  }
  orgSchema {
    ...OrgSchemaFieldPieces
  }
}
